### ISSUE TITLE
Where should a deprecation indicator be located on an artifact?

### ISSUE THREAD

**Issue by chriskilding** [p4em/maven-enhancement-proposals#2]
Thinking about where the artifact deprecation indicator should appear in a Maven repository.

**Comment by chriskilding** [comment]
Starter: it **should not** go in the POM. This is because

- you can't modify published artifacts
- we don't want to make maintainers recompile an artifact just to (un)deprecate it

**Comment by slawekjaranowski** [comment]
`maven-metadata.xml` looks like natural place where we can put such information, and it is on directory / groupId level.

As we see another file can be placed in this location like `tesla-metadata.xml` ( I don't know what and for it is ...)
https://repo1.maven.org/maven2/org/apache/maven/maven/
