### ISSUE TITLE
Consider using GitHub Discussion

### ISSUE THREAD

**Issue by slawekjaranowski** [p4em/maven-enhancement-proposals#5]
In GitHub Discussion we can vote for topic and answers ... 

I think i will be useful in project like it where more of issues is like "Which fields ...", "Where ..." 
so we can vote for specific proposition.

**Comment by chriskilding** [comment]
Ah, didn't know that discussions had polls but issues did not. Yeah we can certainly turn it on once we have assembled some concrete options for each issue.

Also if the Maven community would like, I'd be happy to push this repo over to the apache organization so they could run it. Developers are more likely to find it if it's located there.

**Comment by chriskilding** [comment]
Have enabled discussions :)
